[package]
name = "MyListApi"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
axum = {version = "0.8.3"}
tokio = {version = "1.44", features = ["full"]}
serde = {version = "1.0", features = ["derive"]}
surrealdb = {version = "2.2", features = ["kv-rocksdb"]}
thiserror = {version = "2.0"}
tracing = {version = "0.1"}
tracing-subscriber = {version = "0.3"}
tower-http = {version = "0.6", features = ["cors"]}
